receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
    verbosity: detailed

  otlphttp/loki:
    endpoint: http://loki:3100/otlp

  otlphttp/jaeger:
    endpoint: http://jaeger:4318

  prometheus:
    endpoint: 0.0.0.0:8889

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp/loki]

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp/jaeger]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus]